baseURL: https://litsynp.github.io/
title: litsynp.log
theme: PaperMod

## PaperMod ##
# disableThemeToggle: true
paginate: 20

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: archives
          url: archives
          weight: 5
        - name: search
          url: search/
          weight: 10
        - name: tags
          url: tags/
          weight: 10
        - name: categories
          url: categories/
          weight: 10
        - name: series
          url: series/
          weight: 10

params:
  author: litsynp
  description: Logs by a backend developer
  homeInfoParams:
    Title: litsynp.log
    Content: Logs by a backend developer

  socialIcons:
    - name: "github"
      url: "https://www.github.com/litsynp"
    - name: "email"
      url: "mailto:nocte55is@gmail.com"

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: true

  # BreadCrumb Navigation
  ShowBreadCrumbs: true

  # Table of contents
  ShowToc: true
  TocOpen: true

  # Suggest changes
  editPost:
    URL: "https://github.com/litsynp/litsynp.github.io/blob/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

taxonomies:
  category: categories
  tag: tags
  series: series

outputs:
  home:
    - HTML
    - RSS
    - JSON
