baseURL: https://blog.litsynp.com/
title: litsynp.log
theme: hugo-coder
languagecode: "en"
defaultcontentlanguage: "en"
paginate: 20

googleAnalytics: G-KNPB15W2HP

disqusShortname: litsynp-github-io

# robots.txt
enableRobotsTXT: true

# sitemap.xml
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: posts
          url: posts
          weight: 1
        - name: tags
          url: tags
          weight: 2
        - name: categories
          url: categories
          weight: 3
        - name: series
          url: series
          weight: 4

params:
  author: litsynp
  info: "Memory with a story is more memorable"
  description: "A programming and development blog of litsynp"
  keywords: programming,development,web development,backend development,blog,devlog,developer
  avatarURL: https://avatars.githubusercontent.com/u/42485462?v=4
  env: production
  since: 2021
  # commit: https://github.com/litsynp/litsynp.github.io/tree/"
  math: true
  katex: true
  colorScheme: auto

  favicon_32: "favicon.ico"
  favicon_16: "favicon.ico"

  social:
    - name: "github"
      icon: "fa fa-github fa-2x"
      weight: 1
      url: "https://www.github.com/litsynp"
    - name: "email"
      icon: "fa fa-envelope-square fa-2x"
      weight: 2
      url: "mailto:nocte55is@gmail.com"

taxonomies:
  category: categories
  tag: tags
  series: series
  author: authors

outputs:
  home:
    - HTML
    - RSS
    - JSON
